interface DiscoveryHintProps {
  onClick: () => void;
  revealActive?: boolean;
}

export function DiscoveryHint({ onClick, revealActive }: DiscoveryHintProps) {
  return (
    <button
      type="button"
      className={`discovery-hint${revealActive ? ' discovery-hint--active' : ''}`}
      onClick={onClick}
      aria-pressed={revealActive}
    >
      {revealActive ? 'hide prime structure (P)' : 'waves generated by prime numbers...'}
    </button>
  );
}
